# Generated by Django 5.1.1 on 2024-09-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achatenligne', '0002_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('priorite', models.IntegerField(choices=[(1, 'Faible'), (2, 'Moyenne'), (3, 'Haute')], default=2)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
