# Generated by Django 4.1 on 2024-09-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achatenligne', '0002_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
