# Generated by Django 4.1 on 2024-09-22 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achatenligne', '0002_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('comment', models.TextField()),
                ('rating', models.PositiveIntegerField(default=1)),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
    ]
