# Generated by Django 5.1.1 on 2024-09-27 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achatenligne', '0003_reclamation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_response', models.DateTimeField(auto_now_add=True)),
                ('reclamation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='achatenligne.reclamation')),
            ],
            options={
                'ordering': ['-date_response'],
            },
        ),
    ]
