# Generated by Django 4.1 on 2024-10-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achatenligne', '0003_commande_fournisseur_élémentcommande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='prix_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
