# Generated by Django 4.1 on 2024-09-22 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('achatenligne', '0003_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='achatenligne.category'),
        ),
    ]
