# Generated by Django 4.1 on 2024-10-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achatenligne', '0005_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pdf_version',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
