# Generated by Django 4.1 on 2024-09-23 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achatenligne', '0005_productfeedback_websitefeedback_delete_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitefeedback',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='feedback_images/'),
        ),
    ]
