# Generated by Django 4.1 on 2024-09-24 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achatenligne', '0006_websitefeedback_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductFeedback',
        ),
    ]
